name: Benchmark CI with all Dictionary implementations
# This workflow runs benchmarks for all Dictionary implementations in the repository.

on:  
  workflow_dispatch:
    inputs:
      runs:
        description: 'Number of runs for the benchmark'
        required: false
        default: '5'

jobs:
    run-benchmark-custom:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Install Dependencies
          run: sudo apt-get update && sudo apt-get install -y build-essential bc

        - name: Compile the project
          run: make MODE=release

        - name: Make benchmark script executable
          run: chmod +x ./benchmark.sh

        - name: Run Benchmark script
          run: ./benchmark.sh ${{ github.event.inputs.runs }} bible.txt
