name: C++ CI with Makefile and Google Test

# Define quando o workflow será acionado
on:
  push:
    branches: [ main, master, develop ] # Ajuste para os branches relevantes
  pull_request:
    branches: [ main, master, develop ] # Ajuste para os branches relevantes

jobs:
  build-and-test:
    # Define o tipo de máquina virtual para executar o job
    runs-on: ubuntu-latest # Já vem com g++, make, etc.

    steps:
      # Passo 1: Checkout do código do seu repositório
      - name: Checkout repository
        uses: actions/checkout@v4
        # Se o Google Test estivesse como submódulo, você adicionaria:
        # with:
        #   submodules: 'recursive'
        # Mas como está na pasta 'lib/', o checkout normal é suficiente.

      # Passo 2: Compilar e executar os testes usando o Makefile
      # O target "test" no seu Makefile já compila o necessário (incluindo GTest) e depois executa.
      # O MODE=debug é passado para make para usar CXXFLAGS_DEBUG (que inclui -g para depuração).
      - name: Build and Run tests
        run: make test MODE=debug
        # Você também pode usar MODE=release se preferir testar a versão otimizada,
        # mas para CI, debug é útil para obter mais informações em caso de falha.